name: topographica
channels:
 - ioam
 - conda-forge
 - defaults

dependencies:
 - python=2.7
 - numpy
 - pillow
 - scipy
 - matplotlib
 - cython
 - tk
 - ipython
 - jupyter
 - notebook
# - eigen
 - libpython
 - m2w64-toolchain
 - msys2
 - m2w64-gcc
 - nose            # for tests
 - pyflakes        # for tests
 - pip:
   - gmpy==1.17
   - weave
